### ISSUE TITLE
extract and userID

### ISSUE THREAD

**Issue by itsananyaa** [Saurabh534144/Mini-Voting-System#9]
I didnt understand the concept of extracting in this and also how to know what is the userid?

**Comment by saurabhhirugade** [comment]
I'm not sure what do you mean by extracting but I'll assume it as extracting roll number from userid. So, first of all, let me explain about userid. Userid is a unique identifier used to identify each voter uniquely. As this program was initially created to take classroom elections, we thought to use roll number as a unique identifier. But our college has a special structure to our roll numbers and we call it as "PRN". (See this to understand PRN https://github.com/cognitive-ninja/Mini-Voting-System/issues/4#issuecomment-812884638 ) 

So extraction on PRN is used to validate three things: The Year, The Branch Code and The Roll Number

If initially, you set up reaction for the year "2022" and for branch code "btecs" and there "100" voters then the range of userids will be 2022btecs00001, 2022btecs00002, 2022btecs00003......., 2022btecs00100. No userid will be accepted out of this range. 

I hope your doubt is clear. If not, reply in this thread.
